export const stylesInLine = {
  containerList: {
    height: '90px',
    width: '316px',
    display: 'flex',
    margin: 'auto',
    marginTop: '12px',
    border: '1px solid #EEE',
    borderRadius: '3px',
  },
  containerListSucess: {
    height: '64px',
    width: '316px',
    display: 'flex',
    margin: 'auto',
    marginTop: '12px',
    marginBottom: '15px',
    border: '1px solid #EEE',
    borderRadius: '3px',
  },
  containerText: {
    height: '32px',
    width: '220px',
    paddingTop: '12px',
    fontSize: '13px',
    lineHeight: '16px',
    color: '#212122',
  },
  containerImage: {
    height: '65px',
    width: '65px',
    padding: '10px',
  },
  containerImageSucess: {
    height: '42px',
    width: '42px',
    padding: '10px',
  },
  containerPrice: {
    fontSize: '14px',
    lineHeight: '17px',
    color: '#212122',
    fontWeight: '700',
    paddingTop: '15px',
    textAlign: 'right',
  },
  containerResumePrice: {
    height: '129px',
    width: '354px',
    margin: 'auto',
    borderRadius: '3px',
    border: '1px solid #CCC',
    fontSize: '14px',
    lineHeight: '17px',
    fontWeight: '500',
    color: '#212122',
  },
  containerResumeBox: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '9px 13px 0 13px',
  },
  containerResumeBoxThridChild: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '14px',
    lineHeight: '17px',
    color: '#FF7800',
    padding: '9px 13px 0 13px',
  },
  containerResumeBoxLastChild: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '14px',
    lineHeight: '17px',
    fontWeight: '700',
    padding: '20px 13px 0 13px',
  },
};
