export const styleInline = {
  bigContainerCard: {
    height: '64px',
    width: '320px',
    paddingBottom: '25px',
    display: 'flex',
    flexDirection: 'column',
  },
  mediumContainerCard: {
    height: '64px',
    width: '185px',
    paddingBottom: '25px',
    display: 'flex',
    flexDirection: 'column',
  },
  smallContainerCard: {
    height: '64px',
    width: '145px',
    paddingBottom: '25px',
    display: 'flex',
    flexDirection: 'column',
  },
  labelText: {
    height: '14px',
    width: '129.71px',
    color: ' #CCC',
    fontSize: ' 12px',
    fontWeight: '700',
    lineHeight: '14px',
    paddingBottom: '5px',
  },
  input: {
    height: '45px',
    width: '310px',
    borderRadius: '3px',
    backgroundColor: ' #FFF',
    border: '1px solid #E7E7E7',
    boxShadow: 'inset 0 1px 2px 0 rgba(0,0,0,0.2)',
    color: '#E0E7EE',
    fontSize: '16px',
    letterSpacing: '1.37px',
    lineHeight: '19px',
    padding: '10px',
  },
  inputMedium: {
    height: '45px',
    width: '150px',
    borderRadius: '3px',
    backgroundColor: ' #FFF',
    border: '1px solid #E7E7E7',
    boxShadow: 'inset 0 1px 2px 0 rgba(0,0,0,0.2)',
    color: '#E0E7EE',
    fontSize: '16px',
    letterSpacing: '1.37px',
    lineHeight: '19px',
    paddingLeft: '10px',
  },
  inputSmall: {
    height: '45px',
    width: '135px',
    borderRadius: '3px',
    backgroundColor: ' #FFF',
    border: '1px solid #E7E7E7',
    boxShadow: 'inset 0 1px 2px 0 rgba(0,0,0,0.2)',
    color: '#E0E7EE',
    fontSize: '16px',
    letterSpacing: '1.37px',
    lineHeight: '19px',
    paddingLeft: '10px',
  },
  boxFinally: {
    margin: 'auto',
    marginBottom: '20px',
    height: '73px',
    width: '354px',
    borderRadius: '3px',
    backgroundColor: ' #FFF',
    boxShadow: '1px 1px 5px 0 rgba(0,0,29,0.22)',
    color: ' #000',
    fontSize: '14px',
    lineHeight: '17px',
  },
  textFinally: {
    paddingLeft: '10px',
    paddingTop: '5px',
  },
};
